version: "master-{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "200"
    - ruby_version: "210"
    - ruby_version: "220"

clone_folder: c:\projects\mixlibrary-core
clone_depth: 1
branches:
  only:
    - master

install:
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version

build_script:
  - bundle install

test_script:
  - bundle exec rake